export const TYPES = {
  SET_HYDRATED_SEARCHED_DETAIL: "SET_HYDRATED_SEARCHED_DETAIL",
  ADD_LOCATION_TO_HISTORY: "ADD_LOCATION_TO_HISTORY",
  DELETE_LOCATION: "DELETE_LOCATION",
  SET_SELECTED_LOCATION_DETAIL: "SET_SELECTED_LOCATION_DETAIL",
};
